export const skills = [
  {
    category: 'Development',
    list: [
      'Web Development',
      'JavaScript',
      'HTML',
      'CSS',
      'Solidity',
      'Ethereum',
      'Smart Contracts',
      'Node.js',
      'React',
      'Vue.js',
      'R',
      'Machine Learning',
      'Data Visualization',
      'Embedded Systems',
      'Real-time Software',
      'Ruby on Rails',
      'Python',
      'PHP',
      'Ruby',
      'Java',
      'TypeScript',
      'C#',
      'Go',
      'Mobile App Development',
      'Swift',
      'Objective-C',
      'Kotlin',
      'React Native',
      'Flutter',
      'Ionic',
      'Xamarin',
      'Software Engineering',
      'C++',
      'Rust',
      'Data Science',
      'SQL',
      'SAS',
      'Scala',
      'AI/Machine Learning',
      '.NET',
      'Angular',
      'TensorFlow',
      'PyTorch',
      'Keras',
      'Pandas',
      'Game Development',
      'Unity',
      'Unreal Engine',
      'Godot',
      'Cocos2d',
      'Django',
      'RESTful API Development',
      'NLP',
      'Quality Assurance',
      'Testing',
      'QA Tools'
    ]
  },
  {
    category: 'Design',
    list: [
      'Graphic Design',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'CorelDRAW',
      'Inkscape',
      'UI/UX Design',
      'Sketch',
      'Figma',
      'Adobe XD',
      'InVision',
      'Industrial Design',
      'SolidWorks',
      'AutoCAD',
      'Fusion 360',
      'Rhinoceros',
      '3D Modeling',
      'Blender',
      'ZBrush',
      'Cinema 4D',
      'CAD Design',
      'Motion Design',
      'Print Design',
      'Brand Identity',
      'Packaging Design',
      'Illustration',
      'Typography',
      'Visual Design',
      'Product Design',
      'Art Design',
      'Photoshop',
      'Game Art',
      'Game Design'
    ]
  },
  {
    category: 'Writing & Content',
    list: [
      'Content Writing',
      'Technical Writing',
      'Blogging',
      'Copywriting',
      'Creative Writing',
      'Editing & Proofreading',
      'Article Writing',
      'Ghostwriting',
      'Social Media Content',
      'Scriptwriting',
      'Grant Writing',
      'Resume Writing',
      'Speech Writing',
      'Press Release Writing',
      'Book Writing',
      'Research Writing',
      'Academic Writing',
      'Business Writing'
    ]
  },
  {
    category: 'Marketing & Sales',
    list: [
      'Digital Marketing',
      'SEO/SEM Services',
      'Social Media Marketing',
      'Sales & Lead Generation',
      'Public Relations',
      'Email Marketing',
      'Content Marketing',
      'Market Research',
      'Brand Strategy',
      'Advertising',
      'Influencer Marketing',
      'Affiliate Marketing',
      'E-commerce Marketing',
      'Event Marketing',
      'Marketing Analytics',
      'Customer Relationship Management (CRM)',
      'Marketing Automation'
    ]
  },
  {
    category: 'Business & Management',
    list: [
      'Project Management',
      'Business Consulting',
      'Operations Management',
      'Financial Consulting',
      'Strategic Planning',
      'Human Resources',
      'Supply Chain Management',
      'Risk Management',
      'Business Analysis',
      'Data Analysis',
      'Business Development',
      'Entrepreneurship',
      'Change Management',
      'Organizational Development',
      'Quality Management',
      'Leadership Development'
    ]
  },
  {
    category: 'IT & Networking',
    list: [
      'IT Consulting',
      'AWS',
      'Network Administration',
      'Cisco',
      'Juniper',
      'VMware',
      'Azure',
      'Cybersecurity',
      'Threat Intelligence',
      'CISSP',
      'CISM',
      'Docker',
      'CompTIA Security+',
      'CEH',
      'Database Administration',
      'Oracle DB',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'SQL Server',
      'Cloud Computing',
      'System Administration',
      'IT Support',
      'Virtualization',
      'Network Security',
      'Firewall Management',
      'Wireless Networking',
      'IT Governance',
      'Data Center Management',
      'Kubernetes',
      'Terraform'
    ]
  },
  {
    category: 'Multimedia & Animation',
    list: [
      'Video Production',
      'Adobe Premiere Pro',
      'Final Cut Pro',
      'Avid Media Composer',
      'DaVinci Resolve',
      'Animation',
      'Adobe After Effects',
      'Toon Boom Harmony',
      'Maya',
      '3D Studio Max',
      'Audio Editing',
      'Audacity',
      'Adobe Audition',
      'Pro Tools',
      'Reaper',
      'Logic Pro X',
      'Motion Graphics',
      'Visual Effects',
      '2D Animation',
      '3D Animation',
      'Character Design',
      'Storyboarding',
      'Sound Design',
      'Voice Over',
      'Video Editing',
      'Color Grading',
      'Music Production'
    ]
  },
  {
    category: 'Legal Services',
    list: [
      'Legal Consulting',
      'Contract Law',
      'Intellectual Property Law',
      'Corporate Law',
      'Immigration Law',
      'Family Law',
      'Real Estate Law',
      'Tax Law',
      'Employment Law',
      'International Law',
      'Bankruptcy Law',
      'Environmental Law',
      'Healthcare Law',
      'Criminal Law',
      'Privacy Law',
      'Dispute Resolution'
    ]
  },
  {
    category: 'Customer Service',
    list: [
      'Customer Support',
      'Virtual Assistance',
      'Phone Support',
      'Live Chat Support',
      'Email Support',
      'Technical Support',
      'Order Processing',
      'Data Entry',
      'Appointment Setting',
      'Inbound Call Handling',
      'Outbound Sales Calls',
      'Complaint Resolution',
      'Billing Support',
      'Social Media Support',
      'Help Desk Support',
      'CRM Management'
    ]
  },
  {
    category: 'Learning & Education',
    list: [
      'Tutoring',
      'Curriculum Design',
      'Career Coaching',
      'Online Teaching',
      'Language Teaching',
      'Test Preparation',
      'Instructional Design',
      'E-Learning Development',
      'Educational Consulting',
      'Academic Writing',
      'Lesson Planning',
      'Student Assessment',
      'Learning Management Systems (LMS)',
      'Educational Technology',
      'Adult Education',
      'Special Education'
    ]
  },
  {
    category: 'Engineering & Architecture',
    list: [
      'Architectural Design',
      'Civil Engineering',
      'Electrical Engineering',
      'Mechanical Engineering',
      'Structural Engineering',
      'Environmental Engineering',
      'Chemical Engineering',
      'Industrial Engineering',
      'Automotive Engineering',
      'Aerospace Engineering',
      'Materials Engineering',
      'Process Engineering',
      'Project Engineering',
      'HVAC Design',
      'CAD Drafting',
      'Building Information Modeling (BIM)'
    ]
  },
  {
    category: 'Translation & Languages',
    list: [
      'Translation Services',
      'Interpretation Services',
      'Language Lessons',
      'Linguistic Consulting',
      'Localization',
      'Transcription',
      'Proofreading',
      'Subtitling',
      'Transcreation',
      'Technical Translation',
      'Medical Translation',
      'Legal Translation',
      'Website Localization',
      'Software Localization',
      'Multilingual SEO'
    ]
  }
];

export const mostCommonSkill = [
  'JavaScript',
  'Python',
  'Cloud Computing',
  'Data Analysis',
  'Digital Marketing'
];
