export enum KycStatus {
  PENDING = 'PENDING',
  VALIDATED = 'VALIDATED',
  CANCELLED = 'CANCELLED',
  FINAL_REJECTED = 'FINAL_REJECTED'
}

export enum KycService {
  LIVENESS = 'LIVENESS',
  IDENTITY = 'IDENTITY',
  RESIDENCY = 'RESIDENCY'
}

export enum KycServiceState {
  NOT_STARTED = 'NOT_STARTED',
  SUBMITTED= 'SUBMITTED',
  VALIDATED = 'VALIDATED',
  REJECTED = 'REJECTED',
  FINAL_REJECTED = 'FINAL_REJECTED',
  RESET = 'RESET'
}
