Resources:
  AuthTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-auth-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: wallet
          AttributeType: S
      KeySchema:
        - AttributeName: wallet
          KeyType: HASH
  RatingTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-rating-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: txHash
          AttributeType: S
        - AttributeName: wallet
          AttributeType: S
      KeySchema:
        - AttributeName: txHash
          KeyType: HASH
        - AttributeName: wallet
          KeyType: RANGE
  UserTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-user-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: wallet
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: wallet
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
