Resources:
  AuthTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-auth-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: wallet
          AttributeType: S
      KeySchema:
        - AttributeName: wallet
          KeyType: HASH
  JobTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-job-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: GUID
          AttributeType: S
      KeySchema:
        - AttributeName: GUID
          KeyType: HASH
  KycTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-kyc-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: wallet
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: wallet
          KeyType: RANGE
  ExperienceTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-experience-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: role
          AttributeType: S
      KeySchema:
        - AttributeName: role
          KeyType: HASH
  UserTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-user-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: wallet
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: hasFreelanceProfile
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: wallet
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: HasFreelanceProfileIndex
          KeySchema:
            - AttributeName: hasFreelanceProfile
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
